### ISSUE TITLE
de: for which string types does the word order need to be changed?

### ISSUE THREAD

**Issue by ghost** [obsidianmd/obsidian-translations#461]
Is the word order change of issue #66 required for all strings, or just some?

And if it is only required for some strings, how should one differentiate? Only change the word order of non-sentences? Only change the word order based on string type (i.e. only change description strings and maybe label strings)?

**Comment by FloriF** [comment]
For some 'headings of settings' or label strings, no verb is needed at all to understand (eg., 'Rechtschreibprüfung', 'Lesbare Zeilenlänge'). Forcing a consistent word order would introduce unnecessary complexity (e.g., 'Rechtschreibprüfung aktivieren', 'Lesbare Zeilenlänge einstellen'). This is in regards to the word order issue for the one-line descriptions that are immediately followed by the description (otherwise we would have settings like: 'Standardfarbschema wählen - Wähle das Standardfarbschema für Obsidian' which makes the headings for settings irrelevant).

**So I'd recommend:** sticking to the word order for the short headings where a verb is necessary to understand what the setting corresponds to. For all the other cases we can drop the verbs.

For the description strings, we would need to decide on how/if we address the user. In english, it is not unified if e.g. 'Lets you do XY' or 'Does XY' or even 'Do XY' is used. In german, I would argue for a translation corresponding to the last alternative ('Tue XY
', eg., 'Wähle Farbschema'). The first alternative would lead to longer, more complex strings in the descriptions ('Ermöglicht es Dir, ein Farbschema zu wählen'). The second alternative would be possible, but I think to keep the level of 'formality' of how Obsidian talks to its users in english, the third one would be better.

**So here I'd recommend:** translating the description labels in the format 'Do XY' to keep a unified word order. This would also be in line with the kind of 'higher level' translations of some basic functions like 'Open file'.

Also, the same would apply for the one-word-translations, where we still sometimes use eg. 'Maximieren' at one point, but 'Suche' at another point. Here we should watch out that the translations are easily understandable (eg., 'Lösche' - does this mean that we want Obsidian to delete something, or that it is already deleting something?). 

We should consider creating something like the termbase in other languages (eg., https://github.com/obsidianmd/obsidian-translations/blob/f5bff453e5106e1547b6772a9276fb22dcc15cf4/pt-BR.termbase.md) to write down the translation conventions we are using, regarding the word order.

**Comment by 7aqdxe6f** [comment]
Thanks for taking the time to write this detailed response! I agree, creating a termbase is a good idea.

Option two makes the most sense for description strings, you are right. I also agree on removing superfluous verbs from the headings.

Just to clarify: As I understand issue #66 it is preferable to place the word at the end of the string in the infinitive form. Wouldn't that mean for the description string that we should translate "Farbschema wählen" instead of "Wähle Farbschema"? Or am I missing something? Although this doesn't seem to be achievable for all strings (e.g. the informational string on the aforementioned lines 17 and 18).

**Comment by 42sol-eu** [comment]
Hi, I would try to reanimate the German translation (team).

1. Improve the UI-Translation 
2. Full translation of the Documentation 
3. I will add a German term base in this repository - my first getting my feet wet is a pull request on this repo https://github.com/obsidianmd/obsidian-translations/pull/567

**Comment by ericaxu** [comment]
Feel free to add `de.termbase.json`. Docs are over at https://github.com/obsidianmd/obsidian-docs if you want to contribute.

Closing this and feel free to open a new issue for other issues.
