### ISSUE TITLE
Correspondence: Forward link/Outgoing link/Backlink/Incoming link 

### ISSUE THREAD

**Issue by yo-goto** [obsidianmd/obsidian-translations#476]
Hi, I got confused about the word choice "Outgoing link".
I assumed Obsidian v0.12.4 would have the Forward link plugin which the roadmap says.
Considering the correspondence, not Outgoing link but Forward link is the correct word choice I think.
Otherwise, is there any possibility to change "Backlink" to "Incoming link"?

**Comment by ericaxu** [comment]
Sorry for the confusion, I've changed the card on Trello roadmap.

Outgoing link is an existing term in local graph settings, so we'll continue to use that. I agree that "Incoming links" would be ideal to match "Outgoing links", but because how well known backlinks are in this space, I think it's best to keep it.

Thanks for your concern!

**Comment by yo-goto** [comment]
Ok, I got it.
"Backlink" and "Outgoing link". I'm going to modify translation of these terms as you said.

**Comment by ericaxu** [comment]
Thanks so much!
