### ISSUE TITLE
Add new language Taiwanese Hokkien (nan-TW)

### ISSUE THREAD

**Issue by luke871016** [obsidianmd/obsidian-translations#561]
Hello,

I would like to translate Obsidian to Taiwanese Hokkien (臺灣話文), which is my native language.

The iso code is `nan`, I recommend to add geocode behind since the difference between Taiwanese Hokkien and Southern Min. The json file might be `nan-TW.json`. Thanks!

https://en.wikipedia.org/wiki/Taiwanese_Hokkien
https://iso639-3.sil.org/code/nan

**Comment by ericaxu** [comment]
Hi there, is it very different than `zh-TW`? Would prefer them to stay as one language if possible as I can't find `nan` in the ISO list we usually use (ISO 639-1 two letter codes). https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes

**Comment by ericaxu** [comment]
Let me know if you want to re-open this, thanks!

**Comment by GJRobert** [comment]
Dear Obsidian developers,

I am also from Taiwan and I like Obsidian a lot. Yes, Hokkien, Hakka, Cantonese, Wu, etc., these are very different languages from Mandarin even when written in CJK ideographs ("Hanzi"), because the lexicon vary every here and there. And sometimes when there is no conventional Hanzi notation, an orthography of roman alphabets is used. So `nan-tw` is very different from `zh-tw`.

And since ISO 639-1 cannot cover all known languages, therefore ISO 639-3 which is a exhaustive list with 3 letter codes (https://www.wikiwand.com/en/ISO_639-3) is also widely accepted by Wikimedia, Ethnologue, DokuWiki etc.
(For example, Wikipedia has a lot of language versions of ISO 639-3 languages, including Hokkien (`nan`), Cantonese (`yue`), Hakka (`hak`) etc. and also Taiwanese indigenous languages like ['Amis](https://ami.wikipedia.org/wiki/?oldformat=true), [Paiwan](https://pwn.wikipedia.org/wiki/?oldformat=true). If we see [the list of all Wikipedias](https://en.wikipedia.org/wiki/List_of_Wikipedias?oldformat=true#Detailed_list), we will see in the top 18 wikipedias with > 1 million articles there are 3 languages with ISO 639-3 3-letter codes (Cebuano `ceb`, Egyptian Arabic `arz`, Winaray `war`), and more to follow down the wikipedias list.

We will take care for the localization of Taiwanese Hokkien (`nan-tw`), so please kindly re-open this and add the translation slot for `nan-tw`. Thanks!

Best regards

**Comment by GJRobert** [comment]
Dear Obsidian developers,
I have opened a pull request #839 per the new "Adding new language" procedure.
I can help modifying any documents to follow needed once you allow and merge. Thanks!

Best regards

**Comment by joethei** [comment]
PR #839 has been merged

**Comment by GJRobert** [comment]
Thank you so much @joethei !
